### ISSUE TITLE
[Suggestion] Allow this resource to use the same calls as qb-doorlock

### ISSUE THREAD

**Issue by WEEZOOKARP** [AyPiXt/qb-nui_doorlock#1]
This will allow the script to be used with qb-bankrobbery etc as doors in pacific standard wont function correctly if at all when actually robbing it using the keycard on the door doesn't do anything to unlock it due to the functions being different.
If you don't want to rewrite stuff to work please at least put some instructions on how to use it with stuff like this

**Comment by AyPiXt** [comment]
added to the readme how you can do it have a nice day :)
